### ISSUE TITLE
Tunnels

### ISSUE THREAD

**Issue by inklinea** [fillipe-gsm/python-tsp#28]
Hello, 
Thank you for writing this TSP module It has saved me a lot of time connecting diagrams :)
Is it possible to find a route between tunnels ( either one way or two way ) if each tunnel is a path with a start and end point ? 
So if we enter a tunnel at entry point a, then exit point b of that tunnel would become the next start point ? 
Many thanks Matt.

**Comment by fillipe-gsm** [comment]
Hi, @inklinea, thanks for the interest in the project!

So, can you elaborate a bit more -- perhaps, a lot more -- on your problem?

As far as I understood, you would need to pre-process your distance matrix. The TSP solvers are completely agnostic to the meaning of "nodes"; they just require the distance (or time, or cost, or whatever positive number) from one to another. So, in your case, you could turn the start and end point of each tunnel into different nodes.

For example, suppose your problem has tunnels 1, 2 and 3. Let us call 1a and 1b the start and end points of tunnel 1, and so on. Your `distance_matrix` then would be a `6 x 6` array, such that:

- `distance_matrix[0, 0]` would be the distance from 1a to 1a, which is `0` of course;
- `distance_matrix[0, 1]` would be the distance from 1a to 1b, which could be the length of the tunnel, for example;
- `distance_matrix[0, 2]` would be distance from 1a to 2a. Since 1a is the start of the first tunnel, to get to the start of the second tunnel you would need to add the distance from 1a to 1b and then from 1b to 2a;
- and so on for the other elements.

You mentioned that some tunnels may be one-way or two-way. There are different approaches for handling that. In my previous example, if `distance_matrix[0, 1]` is the distance from 1a to 1b, `distance_matrix[1, 0]` would be the distance in the opposite direction. So, 
- if the tunnel is two-way, you can just plug-in the actual value here. It can be same as `distance_matrix[0, 1]`, for instance;
- if the tunnel is one-way, you could emulate this by writing a very large number in `distance_matrix[1, 0]` (such as 10 times the largest distance in your matrix). 

In any case, it still boils down to pre-processing your distance matrix.

**Comment by fillipe-gsm** [comment]
Okay, thanks for the elaboration and drawing. I _think_ I understood better your problem (but if not, we will probably need a few more rounds of conversation :)).

Anyway, here is a huge text that I hope can be useful for you:

## Core idea

To handle your problem, the simplest approach is again to manipulate the distance matrix. For simplicity, let us consider your last drawing with just tunnels 1, 2 and 3. Following my [first comment](https://github.com/fillipe-gsm/python-tsp/issues/28#issuecomment-1441628347), the actual nodes would be 1a, 1b (start and end points of tunnel 1) and so on for a distance matrix of shape `6 x 6`.

The first row of this matrix gives the distances from 1a to each other node. But as you mentioned, if the "salesperson" is in 1a, the next node **must** be 1b. Then, you can "force" this by providing a `0` distance to 1b and a large number to all the other nodes:

```python
    1a  1b     2a       2b       3a        3b
1a [ 0   0   BIG_NUM  BIG_NUM  BIG_NUM  BIG_NUM]
```
where `BIG_NUM` is obviously a big number, such as 10 times the largest distance among all tunnels. (Notice the distance between 1a to 1a is still 0, of course)

Following this fashion, the second row represents the distances from 1b to the other nodes. I assume from here you can only go the starting points of the _other_ tunnels. Hence, you could have something like:

```python
      1a     1b     2a        2b        3a       3b
1b [BIG_NUM   0   d_{1, 2}  BIG_NUM  d_{1, 3}  BIG_NUM]
```
Here, 
- If the tunnel is one-way only, it cannot go back to 1a, to the distance from 1b to 1a is `BIG_NUM`;
- It can go to any other starting point (2a or 3a), so here I plugged their actual tunnel distances as `d_{1, 2}` and `d_{1, 3}`;
- It cannot go to the ending of the other tunnels, so I used `BIG_NUM` from 2b and 3b.

## Overall suggestion

If you follow this idea, the distance matrix assuming all tunnels are one-way only would become:

```python
      1a         1b       2a       2b        3a       3b
1a [ 0        0        BIG_NUM   BIG_NUM  BIG_NUM   BIG_NUM]
1b [BIG_NUM   0        d_{1, 2}  BIG_NUM  d_{1, 3}  BIG_NUM]
2a [BIG_NUM   BIG_NUM  0         0        BIG_NUM   BIG_NUM]
2b [d_{2, 1}  BIG_NUM  BIG_NUM   0        d_{2, 3}  BIG_NUM]
3a [BIG_NUM   BIG_NUM  BIG_NUM   BIG_NUM  0         0      ]
3b [d_{3, 1}  BIG_NUM  d_{3, 2}  BIG_NUM  BIG_NUM   0      ]
```

(Take a moment to analyse this matrix)

In summary, what is happening is:
- If in a given route, once at a starting point of a tunnel, if the next node is not its ending, then the route distance would be very large. Thus it would be penalized unless its next node is exactly its ending;
  - For example, a route `[1a, 2a, 2b, 3a, 1b, 3b]` would be a bad solution because the distance from 1a to 2a is `BIG_NUM`. Same from 3a to 1b;
  - In contrast, a route `[1a, 1b, 3a, 3b, 2a, 2b]` would not be penalized.
- Similarly, once at a ending point of a tunnel, if the next node is not a starting point of another tunnel, the route would also be penalized.

## Caveats
- Constructing this distance matrix does not look that trivial given the constraints of your problem, but I am sure you can find a way to programmatic extend it to multiple tunnels :);
- You can handle two-way tunnels by changing individual entries. For example, if tunnel 2 were two-way, then 
  - the distance from 2b to 2a instead of `BIG_NUM` would become 0;
  - it is now possible to go from the ending of tunnels 1 and 3 to the ending of tunnel 2, so the distances between 1b and 2b could be finite instead of `BIG_NUM`.
- **This is important:** considering both start and ending points in the same problem means doubling the problem size. Thus, if you were using an exact approach (such as dynamic programming) the execution time could grow a lot, so you would probably need to switch to a heuristic solver.

**Comment by inklinea** [comment]
Many thanks for taking to time to write this excellent information.
I'm going to follow your suggestions, ref the distance matrix construction.

If I succeed, I will post will my results :)

**Comment by fillipe-gsm** [comment]
Hey, @inklinea , do you have an update on this issue?
Did my kinda large text help you in some way?

**Comment by inklinea** [comment]
Hello fillipe, 

I have been testing the matrix you suggested. I found that it's easier to create the full matrix first ( as it is quite quick to do )
then run a simple loop to overwrite entries with BIG_NUM and 0

I've found that `exact.solve_tsp_dynamic_programming(distance_matrix)` gives perfect results but gets a bit slow over 9-10 paths.

The Heuristic methods, sometimes join a start-start or end-end - hopefully that is not my coding :)

I've attached a screen shot. The pink numbers represent the order in which the matrix is made. 
![Screenshot from 2023-03-07 21-47-15](https://user-images.githubusercontent.com/125797722/223561552-ae7d0133-6d52-4723-b697-daaf869a17c7.png)

**Comment by fillipe-gsm** [comment]
@inklinea , from the discussion I can see that there is nothing wrong with the library; you’re just setting up and tweaking your application. 

In that case, I’ll close this issue. Feel free to post your results tough if your pursue this further.
