### ISSUE TITLE
Missing setup.py?

### ISSUE THREAD

**Issue by poke1024** [fillipe-gsm/python-tsp#3]
Hi there. This seems like a very useful lib. Unfortunately `pip` install does not find the package for me and installing manually via `python setup.py install` fails as I cannot find a `setup.py`. Am I missing something?

**Comment by fillipe-gsm** [comment]
Hey, @poke1024, thanks for the interest in the project!
What is your Python version? Does the error you get looks something like this?

```bash
ERROR: Could not find a version that satisfies the requirement python-tsp (from versions: none)
ERROR: No matching distribution found for python-tsp
```

If that is the case, the problem is possibly because your version was below 3.8.

Fortunately, I just updated the lib from 0.1.0 to 0.1.1 so it becomes installable in versions 3.6 to 3.9.
Can you please try again and see if it works now?

**Comment by poke1024** [comment]
Indeed I was using Python 3.7. Tried `pip install python-tsp` again with Python 3.7 and indeed now it works. :-)
