### ISSUE TITLE
Which heuristic to use?

### ISSUE THREAD

**Issue by kevinlinxc** [fillipe-gsm/python-tsp#46]
Is there documentation for which heuristics are good for what case? Also, would it help to put the runtimes of the heuristic algorithms in the docs? It seemed like annealing is n^2, nearest_neigihbour is n^2,  L-K is n^2.2 according to this: http://160592857366.free.fr/joe/ebooks/ShareData/Heuristics%20for%20the%20Traveling%20Salesman%20Problem%20By%20Christian%20Nillson.pdf
 but I can't find the record-record runtime.

**Comment by fillipe-gsm** [comment]
> Is there documentation for which heuristics are good for what case?

I wish there was one :(

As far as I am aware there is no algorithm that beats the others in terms of (i) solution quality, (ii) runtime, (iii) resource utilization, (iv) consistency, and other metrics you can think of. This is part of the reason why there are so many algorithms for the TSP, and why so many more keep emerging.

You could (and probably other people have done it) set up experiments with test problems and a number of solvers, run them in controlled environments a number of times and perform careful analyses of experiments, but most likely you will not end up with a definitive winner. And even if you did, test problems do not necessarily represent well problems we may face in the reality, so the results won't likely be extensible. In fact, ever since I started this repository I've seen issues and received e-mails of people using it for problems I could never think of, ranging from drones, paintings, graphical representation of tunnels etc.

The best answer I can give you unfortunately is that you need to experiment with your problems. An example is the "[A more intricate example](https://github.com/fillipe-gsm/python-tsp#a-more-intricate-example)" section, where I start with a local search solvers, then proceed to Simulated Annealing, then combine the two. This is a sample of the wide exploration one can do when solving such a challenging problem which is the TSP.

> Also, would it help to put the runtimes of the heuristic algorithms in the docs? It seemed like annealing is n^2, nearest_neigihbour is n^2, L-K is n^2.2 according to this

Complexity analyses work well for exact and approximation algorithms. For local search based algorithms (the heuristics we have implemented here) this is not the case. I remember seeing a paper from Thomas Stutzle mentioning the full execution of such algorithms is actually exponential despite having a proper stopping criterion, but I cannot find it right now.

The complexity orders shown in the article you referred are for the _neighborhood search_, which is a single iteration of these algorithms. It depends on the perturbation scheme you choose. For instance, PS1 has `O(n)` steps, PS2 to PS6 have `O(n²)`. Same thing for `O(n^2.2)` in LK; it is just for a single iteration. Because of that, I don't particularly find this information useful as it does not help with the full picture. You are free to disagree tough.
