### ISSUE TITLE
Heuristic solvers do not respect origin

### ISSUE THREAD

**Issue by ShadowLNC** [fillipe-gsm/python-tsp#5]
Thanks for putting the project together!

While the exact solvers do respect the origin, the heuristic solvers do not.
I actually don't want to respect the origin, since I just want the shortest total path (minimum transition cost - don't care about start/finish). I've hacked in a zero start cost and zero end cost by adding a zero start row and zero start column, but the inconsistency leads to incorrect results when using the heuristic solver.

Python 3.8.5, python_tsp 0.1.1

Example:

```
>>> print(distance)
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 2 2 3 2 2 4 3 4 3 1 2 1 3 1 2]
 [0 1 0 2 1 2 2 4 3 4 3 2 2 2 3 2 2]
 [0 1 2 0 3 2 2 4 3 4 3 2 2 2 1 2 2]
 [0 2 1 3 0 3 3 3 2 3 2 1 3 3 2 3 3]
 [0 1 2 2 3 0 2 4 3 4 3 2 2 2 3 2 2]
 [0 1 2 2 3 2 0 4 1 4 3 2 2 2 3 2 2]
 [0 3 4 4 3 4 4 0 3 1 1 2 4 2 3 3 2]
 [0 2 3 3 2 3 1 3 0 3 2 1 3 3 2 3 3]
 [0 3 4 4 3 4 4 1 3 0 1 2 4 3 3 2 2]
 [0 2 3 3 2 3 3 1 2 1 0 1 3 3 2 3 1]
 [0 1 3 3 2 3 3 3 2 3 2 0 3 2 2 2 3]
 [0 1 2 2 3 2 2 4 3 4 3 2 0 2 3 2 2]
 [0 1 3 3 4 3 3 3 4 4 4 2 3 0 4 1 3]
 [0 2 3 1 2 3 3 3 2 3 2 1 3 3 0 3 3]
 [0 1 3 3 4 3 3 4 4 3 4 2 3 1 4 0 3]
 [0 1 2 2 3 2 2 2 3 2 1 2 2 2 3 2 0]]
>>> distance[8][0]
0
>>> d2 = np.array(
... [[0, 1, 2, 3],
... [1, 0, 1, 2],
... [2, 1, 0, 1],
... [3, 2, 1, 0]])
>>> print(python_tsp.exact.solve_tsp_brute_force(d2))
([0, 1, 2, 3], 6)
>>> print(python_tsp.heuristics.solve_tsp_local_search(d2))
([3, 0, 1, 2], 6)
>>> distance[8][5]
3
>>> distance[8][0]
0
>>> distance[0][5]
0
>>> d3 = np.array([[0,1,2,3],[0,0,1,2],[0,1,0,1],[0,2,1,0]])
>>> print(python_tsp.exact.solve_tsp_brute_force(d3))
([0, 1, 2, 3], 3)
>>> print(python_tsp.heuristics.solve_tsp_local_search(d3))
([3, 0, 1, 2], 3)
>>> print(python_tsp.heuristics.solve_tsp_simulated_annealing(d3))
([0, 1, 2, 3], 3)
>>> print(python_tsp.heuristics.solve_tsp_simulated_annealing(d2))
([3, 1, 0, 2], 6)
>>> print(python_tsp.heuristics.solve_tsp_simulated_annealing(distance))
([7, 9, 10, 16, 11, 14, 3, 12, 5, 2, 4, 8, 6, 1, 15, 13, 0], 21)

```

**Comment by fillipe-gsm** [comment]
Hey, @ShadowLNC , thanks for the interest in the project and the detailed example.

Even so, I do not fully understand the issue. The returned path is actually circular, so a path `[0, 1, 2, 3]` is the same as one with `[3, 0, 1, 2]`: both represent a circular path 

- from 0 to go 1;
- from 1 go to 2;
- from 2 go to 3;
- from 3 go to 0.

Thus, all permutations `[0, 1, 2, 3]`, `[1, 2, 3, 0]`, `[2, 3, 0, 1]` and `[3, 0, 1, 2]` are exactly the same, and all of them should have as distance `6` when using the distance matrix `d2` as you showed.

Or are you suggesting the result to always be `[0, 1, 2, 3]` for consistency with the exact solvers?

**Comment by ctyeong** [comment]
I agree with @ShadowLNC because I naturally thought the heuristic solver would work as the exact solver, when scaling up my problem. But I found the difference a while after I spent some time for debugging. If you only care about the total distance, it won't matter much, but if you're interested in getting the path from the origin, it'd be more useful if the returned path starts with the first element. Anyway good to know that this has been raised as an issue here.

**Comment by fillipe-gsm** [comment]
Thanks for the discussion, @ShadowLNC and @ctyeong.

I am working at version 0.2.0 which automatically solves the issue, but I made a hotfix in the linked PR which resulted in version 0.1.2.

The heuristics actually do respect the first node when performing the neighborhooh searches; the problem was the setup, in which the first permutation was inadvertently intialized as a completely random list from `0` to `n - 1` instead of fixing `0` and randomizing the rest. 

This should be fixed in the new version. If not, feel free to open a new issue.

Also, keep in mind that, if you provide a starting point to these methods not starting at 0 (such as `[3, 1, 0, 2]`), the final solution will respect the first node (i.e., it will start at `3` in this example).
